### ISSUE TITLE
Error detection / correction

### ISSUE THREAD

**Issue by trstephen** [trstephen/elec483#3]
Most of the time, casting an IDCT to uint8 will result in a round-down ([e.g.](https://github.com/trstephen/elec483/blob/master/wm_encoder.m#L78)). Infrequently (<10%) it rounds up. We could fix this by spacing out the offsets with a +/-1 buffer but the max offset of 37 chars is 111, ~10% of the DCT value we add it to. This hurts the PSNR ☹️ 

A better strategy is to add error detection / correction codes. To implement this
- Convert the offsets into binary (6 bits needed, or we have to throw out characters to get 32 chars for 5 bits)
- Encode the binary offsets into the DCT blocks starting at the top left of the image
- Encode the error correcting bits in reverse order starting at the bottom right DCT block

We'll have to research a few things
- How to generate the code? A [Hamming code][hc] is the obvious choice.
  - We want to support variable-length watermark phrases. Can we dynamically generate a Hamming code to use?
- I think there was something else but I forgot 😕 

[hc]: https://en.wikipedia.org/wiki/Hamming_code

**Comment by trstephen** [comment]
Prof. Agathoklis suggested some stuff (that he authored) that might be helpful
- [An image watermarking technique with improved resistance to geometric distortions using image feature points][1]
- [A wavelet-based blind and readable image watermarking algorithm][2]

[1]: http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=5407479
[2]: http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1196975

**Comment by houtan1** [comment]
Browsing through the two papers, the first shows something interesting. For adding a watermark to the DCT, instead of using a 0/1 binary implementation, they used a +/-1 binary. Additionally, it looks like the +/-1 is applied to all coefficients of each block, as opposed to only the top value of each.
.
I have a proposition for increasing our error tolerance without the alteration of all coefficients in the DCT block, or having to resort to binary and error checking.
.
What if we used the system we have in place now (addition of mapped-watermark-coefficients to the top-left coefficient of the DCT block) with a new error-busting feature of adding that same coefficient 2 more times (in the positions 1 to the right and 1 below the original top-left) and averaging the 3 difference values once they are extracted?
.
Original Image ........................................................Old Method............................................New Method
XX XX XX XX XX......................................................+12 XX XX XX XX..................................+12 +12 XX XX XX
XX XX XX XX XX.......................................................XX.. XX XX XX XX..................................+12 ..XX XX XX XX
XX XX XX XX XX.......................................................XX.. XX XX XX XX.................................. XX.. ..XX XX XX XX
XX XX XX XX XX.......................................................XX.. XX XX XX XX.................................. XX.. ..XX XX XX XX
.
I'm thinking this new methods would allow us to have better error resilience by giving us the opportunity to average 3 extracted values instead of just one, and to minimize the quality distortion by keeping all DCT coefficient adjustments in the upper left hand side.
.
Excuse the extra periods used as spacers :sweat_smile:

**Comment by trstephen** [comment]
Def want to check the double redundancy method you describe for its effect on the PSNR.
